### ISSUE TITLE
Warning on Alfresco 5.0.c CE

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CesarCapillas/alfresco-share-online-edition-addon#5]
```
What steps will reproduce the problem?
1. copy .jar to tomcat/shared/lib
2. start Alfresco
3.

What is the expected output? What do you see instead?
Mar 21, 2015 12:04:25 AM org.apache.catalina.core.ApplicationContext log
INFORMAÇÕES: Initializing Spring FrameworkServlet 'Spring MVC Dispatcher 
Servlet'
00:04:33,585 ERROR [org.springframework.web.servlet.DispatcherServlet] Context 
initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean 
definition with name 'zk.evaluator.doclib.action.onlineEditMimetype' defined in 
URL 
[jar:file:/opt/alfresco-5.0.c/tomcat/shared/lib/zk-online-edition-0.2.jar!/org/s
pringframework/extensions/surf/zk-online-edition-context.xml]: Could not 
resolve parent bean definition 'evaluator.doclib.action.isMimetype'; nested 
exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No bean named 'evaluator.doclib.action.isMimetype' is defined
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1180)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedBeanDefinition(AbstractBeanFactory.java:1125)



What version of the product are you using? On what operating system?
Centos 7 x64, Alfresco 5.0.c

Please provide any additional information below.
I use the edit online option with Alfresco and FireFox 36 on Linux without 
problems, only the logs show me this warning.

```

Original issue reported on code.google.com by `marcio...@gmail.com` on 28 Mar 2015 at 12:51

**Comment by CesarCapillas** [comment]
Not reproducible, actually Alfresco 5.0.c CE is one of the most tested environments for the plugin.
